#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
# This is for smoother cursor (default is 17)
bspc config pointer_motion_interval 7ms
# Mouse acc
xset m 1 1 &

# Set cursor theme on startuo
xsetroot -cursor_name left_ptr

# Set 60hz
xrandr -r 60

# Set GTK4 mode to light
gsettings set org.gnome.desktop.interface color-scheme prefer-light

# Toggle between English(US) and Czech(QWERTY) keyboard layout with Alt+Shift and Windows+Space
setxkbmap -layout us,cz -variant ,qwerty -option grp:alt_shift_toggle,grp:win_space_toggle

bspc rule -a firefox desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a Bitwarden desktop='^6'


#Autostart applications
picom &
nitrogen --restore &
sudo fusuma --config=/home/qwerti/.config/fusuma/config.yml &
dunst &
polybar &
bitwarden-desktop &
kitty
