#!/bin/bash
picom &
nm-applet &


# Set keyboard layout

# mouse acc
xset m 1 1 &

# 144Hz
xrandr -r 144 &

# Set GTK4 mode to light
gsettings set org.gnome.desktop.interface color-scheme prefer-light &

# Toggle between English(US) and Czech(QWERTY) keyboard layout with Alt+Shift and Windows+Space
setxkbmap -layout us,cz -variant ,qwerty -option grp:alt_shift_toggle,grp:win_space_toggle &

fbxkb &

pcmanfm --desktop &
pcmanfm --set-wallpaper /home/qwerti/.config/penguinxp.png &
